# Generated by Django 4.2.9 on 2024-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='house_number',
        ),
        migrations.AddField(
            model_name='product',
            name='darkweb',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
