# Generated by Django 4.2.9 on 2024-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_house_number_product_darkweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='store.customer'),
        ),
    ]
