# Generated by Django 4.2.9 on 2024-02-16 21:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
