# Generated by Django 4.2.9 on 2024-01-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_categories_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='types',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='categories',
            new_name='Type',
        ),
    ]
