# Generated by Django 4.2.9 on 2024-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
