# Generated by Django 4.2.9 on 2024-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='following', to='store.customer'),
        ),
    ]
