# Generated by Django 4.2.9 on 2024-01-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_name_author_aut_rename_name_category_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='aut',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='ty',
            new_name='name',
        ),
    ]
