# Generated by Django 4.2.9 on 2024-01-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_aut_author_name_rename_cat_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
    ]
