# Generated by Django 4.2.9 on 2024-01-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_name_product_pname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='brand',
        ),
    ]
