# Generated by Django 4.2.9 on 2024-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_category2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
