# Generated by Django 4.2.9 on 2024-01-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_category2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ManyToManyField(blank=True, default=False, to='store.category2'),
        ),
    ]
