# Generated by Django 4.2.9 on 2024-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_category2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviewed',
        ),
        migrations.AlterField(
            model_name='category2',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
