# Generated by Django 4.2.9 on 2024-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ManyToManyField(blank=True, to='store.category2'),
        ),
    ]
